name: Snyk Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@v2
        with:
          snyk-token: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test
        run: snyk test
