name: Snyk Security Scan

on: [push, pull_request]

jobs:
  snyk:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Snyk CLI
      run: npm install -g snyk  # Snyk CLI'yi Windows ortamında kuruyoruz

    - name: Run Snyk to check for vulnerabilities
      run: snyk test  # Snyk test komutunu çalıştırıyoruz
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
